sudo: false

language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - python-dev
    - libbz2-dev
    - zlib1g-dev
    - libcppunit-dev
    - lcov
    - ruby
    - rubygems

script: make all CXX=g++-4.9 && make test CXX=g++-4.9
